# Generated by Django 6.0 on 2026-01-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='age',
        ),
    ]
