# Generated by Django 6.0 on 2026-01-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_remove_userregister_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
