# Generated by Django 6.0 on 2026-01-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_userregister_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='district',
            field=models.CharField(default='Not Selected', max_length=50),
        ),
    ]
