# Generated by Django 6.0 on 2026-01-25 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_userregister_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userregister',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
