# Generated by Django 6.0 on 2026-01-28 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0007_helpquery_helpreply_helpreaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpquery',
            old_name='message',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='helpquery',
            name='status',
        ),
        migrations.RemoveField(
            model_name='helpquery',
            name='subject',
        ),
        migrations.AddField(
            model_name='helpquery',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpquery',
            name='reaction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='helpquery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.userregister'),
        ),
    ]
