# Generated by Django 6.0 on 2026-01-28 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_rename_message_helpquery_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpquery',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helpquery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
