# Generated by Django 6.0 on 2026-01-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_helpquery_replied_at_alter_helpquery_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpreply',
            name='query',
        ),
        migrations.RemoveField(
            model_name='helpreaction',
            name='reply',
        ),
        migrations.DeleteModel(
            name='HelpQuery',
        ),
        migrations.DeleteModel(
            name='HelpReaction',
        ),
        migrations.DeleteModel(
            name='HelpReply',
        ),
    ]
