# Generated by Django 6.0 on 2026-01-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0011_helpquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpquery',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpquery',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
