# Generated by Django 6.0 on 2026-01-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0012_helpquery_answer_helpquery_replied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpquery',
            name='reaction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
