# Generated by Django 6.0 on 2026-01-30 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0014_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='gender',
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.userregister'),
        ),
    ]
