# Generated by Django 6.0 on 2026-01-30 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0015_remove_donor_blood_group_remove_donor_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='available_districts',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.userregister'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
