# Generated by Django 6.0 on 2026-01-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0016_remove_donor_available_districts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
