# Generated by Django 6.0 on 2026-01-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0018_donor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
