# Generated by Django 6.0 on 2026-01-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0020_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='confirmation_file',
            field=models.FileField(blank=True, null=True, upload_to='donor_docs/'),
        ),
    ]
