# Generated by Django 6.0 on 2026-01-30 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0021_donor_confirmation_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='confirmed',
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='confirmation_file',
            field=models.FileField(upload_to='donor_files/'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_phone', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('patient_dob', models.DateField()),
                ('patient_phone', models.CharField(max_length=20)),
                ('relative_phone', models.CharField(max_length=20)),
                ('patient_email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('hospital_name', models.CharField(max_length=150)),
                ('hospital_date', models.DateField()),
                ('hospital_ip_number', models.CharField(max_length=50)),
                ('blood_component', models.CharField(max_length=50)),
                ('id_proof', models.FileField(upload_to='patient_ids/')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.userregister')),
            ],
        ),
    ]
