# Generated by Django 6.0 on 2026-01-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0022_remove_donor_confirmed_alter_donor_blood_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodRequest',
        ),
    ]
