# Generated by Django 6.0 on 2026-01-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0024_bloodrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodRequest',
        ),
    ]
