# Generated by Django 6.0 on 2026-01-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0026_bloodrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.DeleteModel(
            name='BloodRequest',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
