# Generated by Django 6.0 on 2026-01-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0028_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_phone', models.CharField(max_length=15)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('blood_component', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=100)),
                ('relative_phone', models.CharField(max_length=15)),
                ('hospital_name', models.CharField(max_length=150)),
                ('hospital_date', models.DateField()),
                ('hospital_ip_number', models.CharField(max_length=50)),
                ('id_proof', models.FileField(upload_to='blood_request_files/')),
                ('status', models.CharField(choices=[('NOT_SEEN', 'NOT_SEEN'), ('SEEN', 'SEEN')], default='NOT_SEEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.userregister')),
            ],
        ),
    ]
