# Generated by Django 6.0 on 2026-01-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0029_bloodrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='id_proof',
            field=models.FileField(upload_to='blood_requests/'),
        ),
    ]
