# Generated by Django 6.0 on 2026-01-31 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0030_alter_bloodrequest_id_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('last_donation_date', models.DateField()),
                ('medications', models.BooleanField()),
                ('tattoo', models.BooleanField()),
                ('illness', models.BooleanField()),
                ('eligible', models.BooleanField()),
                ('reasons', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.userregister')),
            ],
        ),
    ]
