# Generated by Django 6.0 on 2026-01-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0031_eligibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eligibility',
        ),
    ]
