# Generated by Django 6.0 on 2026-02-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0032_delete_eligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_dob', models.DateField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_blood_group', models.CharField(max_length=5)),
                ('blood_component', models.CharField(max_length=50)),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_date', models.DateField()),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_phone', models.CharField(max_length=15)),
                ('donor_names', models.TextField()),
                ('donor_dobs', models.TextField()),
                ('donor_genders', models.TextField()),
                ('donor_blood_groups', models.TextField()),
                ('donor_phones', models.TextField()),
                ('donor_emails', models.TextField()),
                ('donor_districts', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
