# Generated by Django 6.0 on 2026-02-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0034_donor_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='is_available',
        ),
    ]
