# Generated by Django 6.0 on 2026-02-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0035_remove_donor_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalAssignment',
        ),
    ]
