# Generated by Django 6.0 on 2026-02-03 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0037_donationassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationAssignment',
        ),
    ]
