# Generated by Django 6.0 on 2026-02-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0038_delete_donationassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
