# Generated by Django 6.0 on 2026-02-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0039_donor_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='assignment_locked',
            field=models.BooleanField(default=False),
        ),
    ]
