# Generated by Django 6.0 on 2026-02-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0041_donorassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='assignment_locked',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_available',
        ),
        migrations.DeleteModel(
            name='DonorAssignment',
        ),
    ]
