# Generated by Django 6.0 on 2026-02-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0042_remove_bloodrequest_assignment_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
