# Generated by Django 6.0 on 2026-02-03 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0044_bloodrequest_assignment_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalDonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_blood_group', models.CharField(max_length=10)),
                ('hospital_name', models.CharField(max_length=200)),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_phone', models.CharField(max_length=15)),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_blood_group', models.CharField(max_length=10)),
                ('donor_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='donate.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='donate.donor')),
            ],
        ),
    ]
