# Generated by Django 6.0 on 2026-02-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0045_finaldonationrecord_donorassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorassignment',
            name='blood_request',
        ),
        migrations.RemoveField(
            model_name='donorassignment',
            name='donor',
        ),
        migrations.DeleteModel(
            name='FinalDonationRecord',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='assignment_locked',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_available',
        ),
        migrations.DeleteModel(
            name='DonorAssignment',
        ),
    ]
