# Generated by Django 6.0 on 2026-02-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0046_remove_donorassignment_blood_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
