# Generated by Django 6.0 on 2026-02-03 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0047_donor_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('NOT_SEEN', 'NOT_SEEN'), ('SEEN', 'SEEN'), ('FINALIZED', 'FINALIZED')], default='NOT_SEEN', max_length=20),
        ),
        migrations.CreateModel(
            name='DonorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_phone', models.CharField(max_length=15)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_dob', models.DateField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_blood_group', models.CharField(max_length=10)),
                ('blood_component', models.CharField(max_length=50)),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_date', models.DateField()),
                ('donors', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.bloodrequest')),
            ],
        ),
    ]
