# Generated by Django 6.0 on 2026-02-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0048_alter_bloodrequest_status_donorassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('NOT_SEEN', 'NOT_SEEN'), ('SEEN', 'SEEN')], default='NOT_SEEN', max_length=20),
        ),
    ]
