# Generated by Django 6.0 on 2026-02-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0049_bloodrequest_finalized_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='finalized',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('NOT_SEEN', 'NOT_SEEN'), ('SEEN', 'SEEN'), ('FINALIZED', 'FINALIZED')], default='NOT_SEEN', max_length=20),
        ),
    ]
