# Generated by Django 6.0 on 2026-02-03 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0050_remove_bloodrequest_finalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorassignment',
            name='blood_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='donate.bloodrequest'),
        ),
    ]
