# Generated by Django 6.0 on 2026-02-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0051_alter_donorassignment_blood_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorAssignment',
        ),
    ]
