# Generated by Django 6.0 on 2026-02-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0052_delete_donorassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('NOT_SEEN', 'NOT_SEEN'), ('SEEN', 'SEEN')], default='NOT_SEEN', max_length=20),
        ),
    ]
