# Generated by Django 6.0 on 2026-02-03 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0053_remove_donor_is_available_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.donor')),
            ],
        ),
    ]
