# Generated by Django 6.0 on 2026-02-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0054_bloodrequest_is_fulfilled_donor_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('ASSIGNED', 'ASSIGNED')], default='PENDING', max_length=20),
        ),
    ]
