# Generated by Django 6.0 on 2026-02-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0056_donor_is_available_userregister_last_donated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
