# Generated by Django 6.0 on 2026-02-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0058_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
